name: ExtDN M2 Unit Tests
on: [push, pull_request]

jobs:
  unit:
    uses: customgento/m2-github-actions/.github/workflows/unit.yml@main
    with:
      module_name: CustomGento_YouTubeNoCookie
      composer_name: customgento/module-youtube-no-cookie-m2
